package in.iqing.testwsdl;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.7.0
//
// Created by Quasar Development at 20/06/2016
//
//---------------------------------------------------



public class OperationResult< T>
{
    public java.lang.Exception Exception;
    public T Result;
    public Object Tag;
    public String MethodName;
}
